algumValor = input('Digite alguma coisa: ')
print('O valor ` {} ´ é do tipo {}'.format(algumValor, type(algumValor)))
print('O valor ` {} ´ só tem espaços? {}'.format(algumValor, algumValor.isspace()))
print('O valor ` {} ´ é um número? {}'.format(algumValor, algumValor.isnumeric()))
print('O valor ` {} ´ é alfabético? {}'.format(algumValor, algumValor.isalpha()))
print('O valor ` {} ´ é alfanúmerico? {}'.format(algumValor, algumValor.isalnum()))
print('O valor ` {} ´ é maiúsculo? {}'.format(algumValor, algumValor.isupper()))
print('O valor ` {} ´ é um minúsculo? {}'.format(algumValor, algumValor.islower()))
print('O valor ` {} ´ é capitalizado? {}'.format(algumValor, algumValor.istitle()))